services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-email-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-email_service}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "6435:5432"
    volumes:
      - postgres_email_data:/var/lib/postgresql
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-email_service}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

volumes:
  postgres_email_data:

networks:
  backend:
    driver: bridge
